### ISSUE TITLE
SSR re-attachment is not working

### ISSUE THREAD

**Issue by justinbmeyer** [donejs/bitballs#213] opened 2016-03-19 02:22 UTC
Will have a repeatable test case soon.  cc @matthewp

**Comment by justinbmeyer** [comment] 2016-03-19 02:42
Seems like it happens when there is no games and you try to create a game.

**Comment by justinbmeyer** [comment] 2016-03-19 02:45
I can confirm that the callback here: 

```
this.renderAsync().then(function(result){
```

never gets called.

**Comment by justinbmeyer** [comment] 2016-03-19 02:52
You have to be logged in.

**Comment by matthewp** [comment] 2016-03-19 17:37
So, some other async thing is either not resolving or not running within the Zone. I'll look into it.

From a UX perspective, https://github.com/donejs/done-ssr/issues/123 is really needed so the developer isn't puzzled about what is going on (I know this is for reattachment but same thing applies I think).

**Comment by matthewp** [comment] 2016-03-21 12:55
What URL are you visiting?  Is it http://localhost:5000/?tournamentId=1 ?

Are you sure you have updated dependencies? This sounds like the same bug I was working on last week. I cannot reproduce in master.

**Comment by justinbmeyer** [comment] 2016-03-21 14:13
I'm pretty sure I did. I will check again momentarily.

**Closed** 2016-03-22 00:52 UTC
Labels: bug
