### ISSUE TITLE
Verification email link is missing an /

### ISSUE THREAD

**Issue by ccummings** [donejs/bitballs#195] opened 2016-03-16 17:59 UTC
There is a missing `/` between the `appUrl` and the rest of the link in the email verification here: https://github.com/donejs/bitballs/blob/master/services/users.js#L95

**Comment by justinbmeyer** [comment] 2016-03-16 18:02
Thanks.  The problem is really here: https://github.com/donejs/bitballs/blob/master/package.json#L81

**Comment by justinbmeyer** [comment] 2016-03-16 21:49
Fixed by #196

**Closed by justinbmeyer** 2016-03-16 21:49 UTC
